const API_URL = 'http://45.79.207.223:1999'

const SIGNUP_ENDPOINT = API_URL + '/signup'
const LOGIN_ENDPOINT = API_URL + '/login'

const LINKS_ENDPOINT = API_URL + '/links/top'

const SUMMARIES_ENDPOINT = API_URL + '/summaries'
const TAGS_ENDPOINT = API_URL + '/tags'

const CATS_ENDPOINT = API_URL + '/cats'
const CONTRIBUTORS_ENDPOINT = API_URL + '/contributors'

const TMAP_ENDPOINT = API_URL + '/map'
const TMAP_ABOUT_ENDPOINT = API_URL + '/about'
const TMAP_PFP_ENDPOINT = API_URL + '/pic'

export {
	API_URL,
	CATS_ENDPOINT,
	CONTRIBUTORS_ENDPOINT,
	LINKS_ENDPOINT,
	LOGIN_ENDPOINT,
	SIGNUP_ENDPOINT,
	SUMMARIES_ENDPOINT,
	TAGS_ENDPOINT,
	TMAP_ABOUT_ENDPOINT,
	TMAP_ENDPOINT,
	TMAP_PFP_ENDPOINT,
}
