name: FITM Backend
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [cd]

jobs:
    build:
        defaults:
            run:
                working-directory: backend
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.20'

            - name: Build
              run: go build --tags 'fts5' -v .

            - name: Test
              run: go test --tags 'fts5' -v ./...
